openapi: 3.0.0
info:
  title: Nostr Protocol API
  version: 1.0.0
  description: API specification for the Nostr Protocol based on various NIPs.
paths:
  /events:
    post:
      summary: Publish a new event
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Event'
      responses:
        '200':
          description: Event published
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example: ["OK", "event_id", true, "message"]
  /relay-info:
    get:
      summary: Get relay information
      responses:
        '200':
          description: Relay information document
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RelayInformation'
  /threads:
    get:
      summary: Fetch a flattened discussion thread
      parameters:
        - name: thread_id
          in: query
          required: true
          schema:
            type: string
            description: ID of the root event of the thread
      responses:
        '200':
          description: Flattened discussion thread
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Thread'
components:
  schemas:
    Event:
      type: object
      properties:
        id:
          type: string
          description: 32-byte hex-encoded event id
        pubkey:
          type: string
          description: 32-byte hex-encoded public key of the event creator
        created_at:
          type: integer
          description: Unix timestamp (seconds)
        kind:
          type: integer
          description: Event kind (0-65535)
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: Array of tag arrays
        content:
          type: string
          description: Event content
        sig:
          type: string
          description: 64-byte hex-encoded signature
    RelayInformation:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        pubkey:
          type: string
          description: 32-byte hex-encoded public key
        contact:
          type: string
          description: Contact email
        supported_nips:
          type: array
          items:
            type: integer
        software:
          type: string
        version:
          type: string
        payment_methods:
          type: array
          items:
            type: string
    Thread:
      type: object
      properties:
        thread_id:
          type: string
          description: ID of the root event of the thread
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
          description: Array of events in the thread
    FollowListEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 3
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: Array of arrays '["p", <32-byte hex key>, <relay URL>, <petname>]'
        content:
          type: string
          example: ""
    OpenTimestampsAttestationTag:
      type: array
      items:
        type: string
      example: ["nonce", <OpenTimestamps proof>]
    DNSMapping:
      type: object
      properties:
        domain:
          type: string
        public_key:
          type: string
          description: 32-byte hex-encoded public key
    TXTRecord:
      type: object
      properties:
        name:
          type: string
        pubkey:
          type: string
          description: 32-byte hex-encoded public key
    TaggingConventions:
      type: array
      items:
        type: string
      example: ["e", <event_id>, <relay_url>, <marker>]
    ProofOfWork:
      type: object
      properties:
        difficulty:
          type: integer
          description: Number of leading zeroes in hash
    SubjectTag:
      type: array
      items:
        type: string
      example: ["subject", <subject_text>]
    PrivateDirectMessageEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 14
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["p", <receiver_pubkey>, <relay_url>], ["e", <event_id>, <relay_url>, "reply"]'
        content:
          type: string
          description: Encrypted message content
    RelayPreferences:
      type: object
      properties:
        kind:
          type: integer
          example: 10050
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["relay", <relay_url>]'
        content:
          type: string
          example: ""
    RepostEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 6
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["e", <event_id>, <relay_url>, <marker>], ["p", <pubkey>, <relay_url>]'
        content:
          type: string
          description: Repost content
    LongFormContentEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 30023
        tags:
          type: array
          items:
            type: array
            items:
              type: string
        content:
          type: string
          description: Main text
        title:
          type: string
        summary:
          type: string
        thumbnail:
          type: string
          description: URL to thumbnail
    ExtraMetadataFields:
      type: object
      properties:
        display_name:
          type: string
        website:
          type: string
        banner:
          type: string
          description: URL to banner
        bot:
          type: boolean
    ReactionEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 7
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["e", <event_id>], ["p", <pubkey>], ["a", <kind:pubkey:d-tag>]'
        content:
          type: string
          description: Reaction content (e.g., '+', '-', or emoji)
    TextNoteReferences:
      type: object
      properties:
        kind:
          type: integer
          example: various
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["e", <event_id>, <relay_url>, <marker>], ["p", <pubkey>, <relay_url>]'
        content:
          type: string
          description: Content containing 'nostr:' URLs
    PublicChatEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 42
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["e", <event_id>, <relay_url>, "root"], ["p", <pubkey>, <relay_url>]'
        content:
          type: string
          description: Chat message
        chat_room_id:
          type: string
          description: ID of the chat room
    LabelEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 1985
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["L", <namespace>], ["l", <label>, <namespace>], ["e", <event_id>], ["p", <pubkey>]'
        content:
          type: string
          description: Optional explanation
    SensitiveContentTag:
      type: array
      items:
        type: string
      example: ["content-warning", "Sensitive content"]
    ExternalIdentityTag:
      type: array
      items:
        type: string
      example: ["i", "twitter:@username", "https://proof.url"]
    ListEvent:
      type: object
      properties:
        kind:
          type: integer
          example: various based on list type
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["p", <pubkey>], ["e", <event_id>], ["t", <hashtag>]'
        content:
          type: string
          description: For private items, encrypted JSON array
    ReportEvent:
      type: object
      properties:
        kind:
          type: integer
          example: 1984
        tags:
          type: array
          items:
            type: array
            items:
              type: string
          description: '["e", <event_id>], ["r", <reason>]'
        content:
          type: string
          description: Optional detailed description
